name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight UTC
  workflow_dispatch:              # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5     # Show last 5 activities
          plugin_activity_days: 14     # Look back 14 days
          plugin_activity_filter: all  # Include PRs, issues, reviews, etc.
