name: Update README
on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday at midnight UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for committing back to repo
    steps:
      - uses: actions/checkout@v4
      
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ADITYATIWARI342005
          template: classic
          base: header, activity, community, repositories, metadata  # Enhanced base
          config_timezone: Asia/Kolkata
          
          # Output configuration
          filename: github-metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "Update metrics [skip ci]"
          
          # YOUR ORIGINAL ACTIVITY RADAR PLUGIN
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all
          
          # KROL3'S PROVEN PLUGINS
          plugin_discussions: yes
          
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # ADDITIONAL STABLE PLUGINS FOR COMPREHENSIVE METRICS
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
